from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 543)
        MainWindow.setMouseTracking(False)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(510, 200, 170, 271))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.navigation_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.navigation_layout.setContentsMargins(0, 0, 0, 0)
        self.navigation_layout.setObjectName("navigation_layout")
        self.frequency = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.frequency.setAutoFillBackground(False)
        self.frequency.setMaximum(5)
        self.frequency.setProperty("value", 0)
        self.frequency.setSliderPosition(0)
        self.frequency.setOrientation(QtCore.Qt.Vertical)
        self.frequency.setObjectName("frequency")
        self.navigation_layout.addWidget(self.frequency)
        self.tail_rolling = QtWidgets.QDial(self.horizontalLayoutWidget_2)
        self.tail_rolling.setMinimum(-60)
        self.tail_rolling.setMaximum(60)
        self.tail_rolling.setObjectName("tail_rolling")
        self.navigation_layout.addWidget(self.tail_rolling)
        self.tail_pitching = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.tail_pitching.setMinimum(-60)
        self.tail_pitching.setMaximum(60)
        self.tail_pitching.setPageStep(5)
        self.tail_pitching.setOrientation(QtCore.Qt.Vertical)
        self.tail_pitching.setObjectName("tail_pitching")
        self.navigation_layout.addWidget(self.tail_pitching)
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(10, 30, 80, 23))
        self.connect.setObjectName("connect")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 421, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(460, 140, 261, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.navigation_title_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.navigation_title_layout.setContentsMargins(0, 0, 0, 0)
        self.navigation_title_layout.setObjectName("navigation_title_layout")
        self.frequency_title = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.frequency_title.setObjectName("frequency_title")
        self.navigation_title_layout.addWidget(self.frequency_title)
        self.rolling_title = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.rolling_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rolling_title.setObjectName("rolling_title")
        self.navigation_title_layout.addWidget(self.rolling_title)
        self.pitching_title = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.pitching_title.setObjectName("pitching_title")
        self.navigation_title_layout.addWidget(self.pitching_title)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 30, 101, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.frequency_title.setPlainText(_translate("MainWindow", "Frequency"))
        self.rolling_title.setPlainText(_translate("MainWindow", "Rolling"))
        self.pitching_title.setPlainText(_translate("MainWindow", "Pitching"))
        self.pushButton.setText(_translate("MainWindow", "Measure Force"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
